name: Deploy Azure spot VMs

on:
  workflow_dispatch:   
    inputs:
       action:
        description: "Action type"
        required: true
        type : choice
        options:
          - Create
          - Destroy
       note:
        description: "Ensure to review TF plan before you approve it"
        required: false
        type : boolean
  #push:
  #push:
  # branches:
  #   - main

env:
  TF_VAR_ADMIN_PASSWORD: ${{ secrets.AZURE_VM_ADMIN_PASSWORD }}
  TF_VAR_userA_password: ${{ secrets.AZURE_VM_USERA_PASSWORD }}
  TF_VAR_userB_password: ${{ secrets.AZURE_VM_USERB_PASSWORD }}
  ARM_CLIENT_ID        : ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET    : ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID  : ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID        : ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary

      - name: Upload plan file
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: Terraform/tfplan.binary


  terraform-apply:
    needs: terraform-plan
    if: ${{ github.event.inputs.action== 'Create' }}
    environment: critical
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform init

      - name: Download plan file
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: Terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan.binary

  terraform-destroy:
    needs: terraform-plan
    if: ${{ github.event.inputs.action== 'Destroy' }}
    environment: critical
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform init

      - name: Download plan file
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: Terraform

      - name: Terraform Destroy
        run: terraform destroy -auto-approve tfplan.binary
