name: Deploy SPC Resources

on:
  workflow_dispatch:   
    inputs:
      cloud:
        description: "Target cloud"
        required: true
        type: choice
        options:
          - AWS
          - Azure
      action:
        description: "Action type"
        required: true
        type : choice
        options:
          - Create
          - Destroy
          - PIP_Recycle
      check:
        description: "confirm 'Apply' after 'Plan' review [recommended]"
        default: false
        type : boolean

      target_ip:
        description: "Enter PublicIP to-be recycled, if any"
        required: false

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  TF_VAR_cloud         : ${{ github.event.inputs.cloud }}
  TF_VAR_admin_password: ${{ secrets.AZURE_VM_ADMIN_PASSWORD }}
  TF_VAR_userA_password: ${{ secrets.AZURE_VM_USERA_PASSWORD }}
  TF_VAR_userB_password: ${{ secrets.AZURE_VM_USERB_PASSWORD }}
  TF_VAR_pgsql_password: ${{ secrets.AZURE_VM_APP_PGSQL_PASSWORD }}

  # Azure secrets
  ARM_CLIENT_ID        : ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET    : ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID  : ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID        : ${{ secrets.AZURE_TENANT_ID }}

  # AWS secrets
  AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #AWS_DEFAULT_REGION   : ${{ secrets.AWS_DEFAULT_REGION }}


jobs:
  terraform-plan:
    if: ${{ github.event.inputs.action == 'Create' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary

      - name: Upload plan file
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: Terraform/tfplan.binary

  terraform-apply:
    needs: terraform-plan
    if: ${{ github.event.inputs.action== 'Create' && github.event.inputs.check == 'true' }}
    environment: critical
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform init

      - name: Download plan file
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: Terraform

      - name: Terraform Apply
        run:  terraform apply -auto-approve tfplan.binary


  PIP-Recycle:
    needs: terraform-apply
    if: ${{ always() && github.event.inputs.action == 'PIP_Recycle' && github.event.inputs.target_ip  != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init Terraform
        run: terraform init

      - name: show TF output
        run: terraform output -json | jq .


      - name: Find resource by IP
        id: find_resource
        run: |
          target_ip="${{ github.event.inputs.target_ip }}"
          terraform output -json > tf_outputs.json
          resource=$(jq -r --arg ip "$target_ip" '
          .backend_ip_map_region1.value | to_entries[] | select(.value.ip == $ip) | .value.resource_name
          // .discovery_ip_map_region1.value | to_entries[] | select(.value.ip == $ip) | .value.resource_name
          ' tf_outputs.json)
          echo "resource=$resource" >> $GITHUB_OUTPUT

      - name: Taint resource
        run: terraform taint ${{ steps.find_resource.outputs.resource }}

      - name: Apply changes
        run: terraform apply -auto-approve


  terraform-destroy:
    needs: terraform-apply
    if: ${{ always() && github.event.inputs.action == 'Destroy' }}
    environment: critical
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
