name: Deploy SPC Resources

on:
  workflow_dispatch:   
    inputs:
      cloud:
        description: "Target cloud"
        required: true
        type: choice
        options:
          - AWS
          - Azure
      action:
        description: "Action type"
        required: true
        type : choice
        options:
          - Create
          - Destroy
          - PIP_Recycle

      use_spot:
        description: "Launch Runner as Spot instances"
        default: false
        type : boolean
      check:
        description: "Ensure plan is reviewed manually [Required for Apply]"
        default: false
        type : boolean

      target_ip:
        description: "[optional] Enter PublicIP to-be recycled, when needed (Example: 100.10.100.10)"
        required: false


env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  TF_VAR_cloud         : ${{ github.event.inputs.cloud }}
  TF_VAR_admin_password: ${{ secrets.AZURE_VM_ADMIN_PASSWORD }}
  TF_VAR_userA_password: ${{ secrets.AZURE_VM_USERA_PASSWORD }}
  TF_VAR_userB_password: ${{ secrets.AZURE_VM_USERB_PASSWORD }}
  TF_VAR_pgsql_password: ${{ secrets.AZURE_VM_APP_PGSQL_PASSWORD }}
  TF_VAR_use_spot      : ${{ github.event.inputs.use_spot }}


  # Azure secrets
  ARM_CLIENT_ID        : ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET    : ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID  : ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID        : ${{ secrets.AZURE_TENANT_ID }}

  # AWS secrets
  AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #AWS_DEFAULT_REGION   : ${{ secrets.AWS_DEFAULT_REGION }}



jobs:
  terraform-plan:
    if: ${{ github.event.inputs.action == 'Create' || github.event.inputs.action == 'PIP_Recycle' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform init

      - name: Show TF output
        if: ${{ github.event.inputs.action == 'PIP_Recycle' && github.event.inputs.target_ip != '' }}
        run: terraform output -json | jq .

      - name: Find Taint Resource
        if: ${{ github.event.inputs.action == 'PIP_Recycle' && github.event.inputs.target_ip != '' }}
        id: find_resource
        run: |
          target_ip=$(echo "${{ github.event.inputs.target_ip }}" | xargs)
           resource=$(terraform output -json | jq -r --arg ip "$target_ip" '
            [
              (.backend_ip_map_region1.value | to_entries[]? | select(.value.ip == $ip) | .value.resource_name),
              (.backend_ip_map_region2.value | to_entries[]? | select(.value.ip == $ip) | .value.resource_name),
              (.discovery_ip_map_region1.value | to_entries[]? | select(.value.ip == $ip) | .value.resource_name),
              (.discovery_ip_map_region2.value | to_entries[]? | select(.value.ip == $ip) | .value.resource_name)
            ]
            | map(select(. != null))
            | .[0]
          ')
          echo "resource=$resource"
          echo "resource=$resource" >> $GITHUB_OUTPUT

      - name: Apply Taint
        if: ${{ github.event.inputs.action == 'PIP_Recycle' && github.event.inputs.target_ip != '' }}
        run: terraform taint ${{ steps.find_resource.outputs.resource }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary

      - name: Upload plan file
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: Terraform/tfplan.binary





  terraform-apply:
    needs: terraform-plan
    if: ${{ (github.event.inputs.action == 'Create' || github.event.inputs.action == 'PIP_Recycle') && github.event.inputs.check == 'true' }}
    environment: critical
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform init

      - name: Download plan file
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: Terraform

      - name: Terraform Apply
        run:  terraform apply -auto-approve tfplan.binary





  terraform-destroy:
    needs: terraform-apply
    if: ${{ always() && github.event.inputs.action == 'Destroy' }}
    environment: critical
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
